'use server'
import {createHash} from 'node:crypto'
import {revalidatePath} from 'next/cache'
import {redirect} from 'next/navigation'
import {createClient} from '../../../lib/supabase/server'
import {parseNatsPib,type ParsedPib} from '../../../lib/notam/pib-parser'
export type NotamActionResult={ok:boolean;message:string;importRunId?:string}
export type EnforcementReadiness={ready:boolean;reasons:string[];configured_mode:'MONITOR'|'ENFORCED';effective_feed_state:string;fail_safe_active:boolean;latest_report_reference:string|null;coverage_end:string|null;matched_records:number;unmatched_records:number;review_required:number;total_map_areas:number;would_show:number;would_hide:number}
export type NotamPreviewResult={ok:boolean;message:string;preview?:{parsed:ParsedPib;fileName:string;sha256:string}}
async function adminClient(){const supabase=await createClient();const {data,error}=await supabase.auth.getUser();if(error||!data.user)redirect('/admin/login');const {data:admin}=await supabase.from('admin_profiles').select('account_status').eq('user_id',data.user.id).maybeSingle();if(!admin||admin.account_status!=='ACTIVE')throw new Error('Active administrator required');return supabase}
async function extractPdfText(data:Uint8Array){const canvas=await import('@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,ImageData:canvas.ImageData,Path2D:canvas.Path2D});const worker=await import('pdfjs-dist/legacy/build/pdf.worker.mjs');Object.assign(globalThis,{pdfjsWorker:worker});const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const pdf=await pdfjs.getDocument({data}).promise;const pages:string[]=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const content=await page.getTextContent();let out='',lastY:number|null=null;for(let i=0;i<content.items.length;i++){const raw=content.items[i];if(!('str' in raw))continue;const y=Math.round(raw.transform[5]);if(lastY!==null&&Math.abs(y-lastY)>2)out+='\n';else if(out&&!out.endsWith('\n'))out+=' ';out+=raw.str;lastY=y;if(raw.hasEOL){out+='\n';lastY=null}}pages.push(out)}return pages.join('\n\f\n')}
export async function previewNotamPib(formData:FormData):Promise<NotamPreviewResult>{try{await adminClient();const value=formData.get('pib');if(!(value instanceof File))return{ok:false,message:'Select a NATS PIB PDF.'};if(!value.name.toLowerCase().endsWith('.pdf'))return{ok:false,message:'Select the original NATS PIB PDF.'};if(value.size===0||value.size>900_000)return{ok:false,message:'The PDF must be between 1 byte and 900 KB.'};const bytes=new Uint8Array(await value.arrayBuffer());const hash=createHash('sha256').update(bytes).digest('hex');const text=await extractPdfText(bytes);const parsed=parseNatsPib(text);return{ok:true,message:'PIB read successfully.',preview:{parsed,fileName:value.name,sha256:hash}}}catch(error){return{ok:false,message:error instanceof Error?error.message:'The PDF could not be read on the DASS server.'}}}
export async function stageNotamPib(payload:ParsedPib&{file_name:string;file_sha256:string}):Promise<NotamActionResult>{try{if(!payload.file_name.toLowerCase().endsWith('.pdf'))return{ok:false,message:'Select the original NATS PDF file.'};if(!/^[0-9a-f]{64}$/.test(payload.file_sha256))return{ok:false,message:'The PDF fingerprint is invalid.'};if(payload.items.length===0||payload.items.length>1000)return{ok:false,message:'The parsed PIB contains an unexpected number of records.'};const supabase=await adminClient();const {data,error}=await supabase.rpc('admin_stage_notam_pib',{p_manifest:{...payload.manifest,file_name:payload.file_name,file_sha256:payload.file_sha256},p_items:payload.items});if(error){const raw=error.message??'';if(raw.includes('already been staged'))return{ok:false,message:'This exact PIB PDF has already been imported.'};return{ok:false,message:'DASS could not stage the PIB. No NOTAM picture has changed.'}}revalidatePath('/admin/notam');return{ok:true,message:'PIB staged for review. The operational NOTAM picture has not changed.',importRunId:String(data)}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function resolveNotamPibItem(formData:FormData):Promise<NotamActionResult>{try{const itemId=String(formData.get('item_id')??''),validFrom=String(formData.get('valid_from')??''),validUntil=String(formData.get('valid_until')??''),justification=String(formData.get('justification')??'').trim();if(!itemId)return{ok:false,message:'Missing PIB review item.'};if(!validFrom||!validUntil||!Number.isFinite(Date.parse(validFrom))||!Number.isFinite(Date.parse(validUntil))||Date.parse(validUntil)<=Date.parse(validFrom))return{ok:false,message:'Enter a valid UTC start and end time.'};if(justification.length<10)return{ok:false,message:'Enter a justification of at least 10 characters.'};const supabase=await adminClient();const {error}=await supabase.rpc('admin_resolve_notam_import_item',{p_item_id:itemId,p_valid_from:validFrom,p_valid_until:validUntil,p_resolution_note:justification});if(error){const raw=error.message??'';if(raw.includes('within PIB coverage'))return{ok:false,message:'The resolved times must remain inside the PIB coverage period.'};if(raw.includes('coverage has expired'))return{ok:false,message:'This PIB has expired and can no longer be amended.'};return{ok:false,message:'DASS could not resolve this schedule. No NOTAM picture has changed.'}}revalidatePath('/admin/notam');return{ok:true,message:'Schedule resolution recorded in the audit trail.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function applySupplement077(importRunId:string):Promise<NotamActionResult>{try{const supabase=await adminClient();const {error}=await supabase.rpc('admin_apply_tda_supplement_077',{p_import_run_id:importRunId});if(error){const raw=error.message??'';if(raw.includes('not reviewable'))return{ok:false,message:'This PIB has expired or is no longer reviewable.'};return{ok:false,message:'DASS could not apply Supplement 077/2026. No NOTAM picture has changed.'}}revalidatePath('/admin/notam');return{ok:true,message:'Supplement 077/2026 geometry and vertical limits recorded for EGD397A/B.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function setNotamEnforcement(mode:'MONITOR'|'ENFORCED',confirmation:string):Promise<NotamActionResult>{try{const supabase=await adminClient();const {error}=await supabase.rpc('admin_set_notam_visibility_mode',{p_mode:mode,p_confirmation:confirmation});if(error){const raw=error.message??'';if(raw.includes('ENFORCEMENT_NOT_READY'))return{ok:false,message:'Enforcement readiness has changed or is incomplete. Refresh and resolve every blocker.'};if(raw.includes('CONFIRMATION_REQUIRED'))return{ok:false,message:'The confirmation phrase does not match.'};return{ok:false,message:'DASS could not change the visibility mode.'}}revalidatePath('/admin/notam');revalidatePath('/');return{ok:true,message:mode==='ENFORCED'?'NOTAM enforcement enabled. Only NOTAM-backed or actively overridden areas are shown while the feed remains current.':'MONITOR mode restored. All current AIP areas are visible.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function publishNotamPib(importRunId:string):Promise<NotamActionResult>{try{const supabase=await adminClient();const {error}=await supabase.rpc('admin_publish_notam_pib',{p_import_run_id:importRunId});if(error){const raw=error.message??'';if(raw.includes('PIB_REVIEW_REQUIRED'))return{ok:false,message:'Resolve every review-required schedule before publishing.'};if(raw.includes('coverage has expired'))return{ok:false,message:'This PIB has expired. Generate and import a new briefing.'};return{ok:false,message:'DASS could not merge this PIB. The existing NOTAM plan remains in force.'}}revalidatePath('/admin/notam');revalidatePath('/operator');revalidatePath('/');return{ok:true,message:'The reviewed PIB has been merged into the forward NOTAM plan.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function discardNotamPib(importRunId:string,reason:string):Promise<NotamActionResult>{try{if(reason.trim().length<5)return{ok:false,message:'Enter a reason of at least five characters.'};const supabase=await adminClient();const {error}=await supabase.rpc('admin_discard_notam_pib',{p_import_run_id:importRunId,p_reason:reason.trim()});if(error)return{ok:false,message:'DASS could not discard this staged PIB.'};revalidatePath('/admin/notam');return{ok:true,message:'The staged PIB was discarded without changing the operational picture.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
