'use server'
import {revalidatePath} from 'next/cache'
import {redirect} from 'next/navigation'
import {createClient} from '../../../lib/supabase/server'
import type {ParsedPib} from '../../../lib/notam/pib-parser'
export type NotamActionResult={ok:boolean;message:string;importRunId?:string}
async function adminClient(){const supabase=await createClient();const {data,error}=await supabase.auth.getUser();if(error||!data.user)redirect('/admin/login');const {data:admin}=await supabase.from('admin_profiles').select('account_status').eq('user_id',data.user.id).maybeSingle();if(!admin||admin.account_status!=='ACTIVE')throw new Error('Active administrator required');return supabase}
export async function stageNotamPib(payload:ParsedPib&{file_name:string;file_sha256:string}):Promise<NotamActionResult>{try{if(!payload.file_name.toLowerCase().endsWith('.pdf'))return{ok:false,message:'Select the original NATS PDF file.'};if(!/^[0-9a-f]{64}$/.test(payload.file_sha256))return{ok:false,message:'The PDF fingerprint is invalid.'};if(payload.items.length===0||payload.items.length>1000)return{ok:false,message:'The parsed PIB contains an unexpected number of records.'};const supabase=await adminClient();const {data,error}=await supabase.rpc('admin_stage_notam_pib',{p_manifest:{...payload.manifest,file_name:payload.file_name,file_sha256:payload.file_sha256},p_items:payload.items});if(error){const raw=error.message??'';if(raw.includes('already been staged'))return{ok:false,message:'This exact PIB PDF has already been imported.'};return{ok:false,message:'DASS could not stage the PIB. No NOTAM picture has changed.'}}revalidatePath('/admin/notam');return{ok:true,message:'PIB staged for review. The operational NOTAM picture has not changed.',importRunId:String(data)}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function publishNotamPib(importRunId:string):Promise<NotamActionResult>{try{const supabase=await adminClient();const {error}=await supabase.rpc('admin_publish_notam_pib',{p_import_run_id:importRunId});if(error){const raw=error.message??'';if(raw.includes('coverage has expired'))return{ok:false,message:'This PIB has expired. Generate and import a new briefing.'};return{ok:false,message:'DASS could not publish this PIB. The previous NOTAM picture remains in force.'}}revalidatePath('/admin/notam');revalidatePath('/operator');revalidatePath('/');return{ok:true,message:'The reviewed PIB picture has been published.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
export async function discardNotamPib(importRunId:string,reason:string):Promise<NotamActionResult>{try{if(reason.trim().length<5)return{ok:false,message:'Enter a reason of at least five characters.'};const supabase=await adminClient();const {error}=await supabase.rpc('admin_discard_notam_pib',{p_import_run_id:importRunId,p_reason:reason.trim()});if(error)return{ok:false,message:'DASS could not discard this staged PIB.'};revalidatePath('/admin/notam');return{ok:true,message:'The staged PIB was discarded without changing the operational picture.'}}catch{return{ok:false,message:'DASS could not verify the administrator session.'}}}
