'use client'
import {useMemo,useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import {parseNatsPib,type ParsedPib} from '../../../lib/notam/pib-parser'
import {discardNotamPib,publishNotamPib,stageNotamPib} from './actions'
type Run={id:string;report_reference:string|null;pib_reference:string|null;file_name:string|null;coverage_start:string|null;coverage_end:string|null;sync_status:string;received_count:number;matched_count:number;unmatched_count:number;warning_count:number;started_at:string;published_at:string|null;error_summary:string|null}
type Item={id:string;import_run_id:string;notam_number:string;q_code:string;event_kind:string;designator:string|null;valid_from:string|null;valid_until:string|null;match_status:string;schedule_status:string;included:boolean;review_note:string|null}
type Preview={parsed:ParsedPib;fileName:string;sha256:string}
function utc(v:string|null){return v?new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))+' UTC':'—'}
async function sha256(buffer:ArrayBuffer){const digest=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function pdfText(buffer:ArrayBuffer){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(buffer)}).promise;const pages:string[]=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const content=await page.getTextContent();let out='',lastY:number|null=null;for(const raw of content.items){if(!('str' in raw))continue;const y=Math.round(raw.transform[5]);if(lastY!==null&&Math.abs(y-lastY)>2)out+='\n';else if(out&&!out.endsWith('\n'))out+=' ';out+=raw.str;lastY=y;if(raw.hasEOL){out+='\n';lastY=null}}pages.push(out)}return pages.join('\n\f\n')}
export default function NotamPibImporter({runs,items}:{runs:Run[];items:Item[]}){const router=useRouter();const [preview,setPreview]=useState<Preview|null>(null),[busyLabel,setBusyLabel]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[discardReason,setDiscardReason]=useState('');const [pending,startTransition]=useTransition();const staged=runs.find(r=>r.sync_status==='STARTED')??null;const stagedItems=useMemo(()=>staged?items.filter(i=>i.import_run_id===staged.id):[],[staged,items]);
 async function selectFile(file:File|null){setPreview(null);setMessage('');setError('');if(!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){setError('Select a NATS PIB PDF.');return}if(file.size>10_000_000){setError('The PDF exceeds the 10 MB import limit.');return}setBusyLabel('Reading and validating PDF…');try{const buffer=await file.arrayBuffer();const [text,hash]=await Promise.all([pdfText(buffer),sha256(buffer)]);setPreview({parsed:parseNatsPib(text),fileName:file.name,sha256:hash})}catch(e){setError(e instanceof Error?e.message:'The PDF could not be parsed.')}finally{setBusyLabel('')}}
 function stage(){if(!preview)return;setError('');setMessage('');startTransition(async()=>{const result=await stageNotamPib({...preview.parsed,file_name:preview.fileName,file_sha256:preview.sha256});if(!result.ok){setError(result.message);return}setMessage(result.message);setPreview(null);router.refresh()})}
 function publish(){if(!staged)return;setError('');setMessage('');startTransition(async()=>{const result=await publishNotamPib(staged.id);if(!result.ok){setError(result.message);return}setMessage(result.message);router.refresh()})}
 function discard(){if(!staged)return;setError('');setMessage('');startTransition(async()=>{const result=await discardNotamPib(staged.id,discardReason);if(!result.ok){setError(result.message);return}setDiscardReason('');setMessage(result.message);router.refresh()})}
 const included=preview?.parsed.items.filter(i=>i.included).length??0,review=preview?.parsed.items.filter(i=>i.schedule_status==='REVIEW_REQUIRED').length??0
 return <><section style={panel}><div style={eyebrow}>CONTROLLED MANUAL INGESTION</div><h2 style={{margin:'5px 0 7px'}}>Import NATS Area PIB</h2><p style={copy}>Upload the original EGTT/EGPX Area PIB PDF. Parsing and staging do not alter the operational picture; publication requires a separate confirmation.</p><label style={{display:'block',border:'1px dashed #49687a',borderRadius:'10px',padding:'17px',textAlign:'center',cursor:staged?'not-allowed':'pointer',color:'#dceef7',background:'#091720'}}><strong>{busyLabel||'Choose NATS PIB PDF'}</strong><input type="file" accept="application/pdf,.pdf" disabled={Boolean(staged)||Boolean(busyLabel)||pending} onChange={e=>void selectFile(e.target.files?.[0]??null)} style={{display:'block',margin:'10px auto 0',maxWidth:'100%'}}/></label>{staged&&<div style={warning}>A PIB is already staged. Publish or discard it before importing another.</div>}
 {preview&&<div style={reviewBox}><div style={stats}><Stat label="Report" value={preview.parsed.manifest.report_reference}/><Stat label="PIB reference" value={preview.parsed.manifest.pib_reference||'—'}/><Stat label="Coverage" value={`${utc(preview.parsed.manifest.coverage_start)} – ${utc(preview.parsed.manifest.coverage_end)}`}/><Stat label="Resolved activations" value={String(included)}/><Stat label="Review required" value={String(review)}/></div>{preview.parsed.warnings.length>0&&<div style={warning}>{preview.parsed.warnings.map(w=><div key={w}>{w}</div>)}</div>}<button type="button" disabled={pending} onClick={stage} style={primary}>{pending?'Staging…':'Stage PIB for review'}</button></div>}</section>
 {staged&&<section style={{marginTop:'20px'}}><h2>Staged review</h2><div style={stagedBox}><div style={stats}><Stat label="Report" value={staged.report_reference??'—'}/><Stat label="Coverage" value={`${utc(staged.coverage_start)} – ${utc(staged.coverage_end)}`}/><Stat label="Parsed records" value={String(staged.received_count)}/><Stat label="Matched activations" value={String(staged.matched_count)}/><Stat label="Warnings" value={String(staged.warning_count)}/></div><div style={itemList}>{stagedItems.map((item,index)=><div key={item.id} style={{padding:'10px 12px',borderTop:index?'1px solid #182b38':0,display:'grid',gridTemplateColumns:'minmax(100px,.7fr) minmax(130px,.8fr) minmax(190px,1.5fr)',gap:'10px',fontSize:'10px'}}><strong style={{color:item.included?'#84e8b0':item.schedule_status==='REVIEW_REQUIRED'?'#ff9299':'#91a6b8'}}>{item.designator??'No UK DA'} · {item.event_kind}</strong><span>{item.notam_number} · {item.q_code}</span><span style={{color:'#91a6b8'}}>{item.included?`${utc(item.valid_from)} – ${utc(item.valid_until)}`:item.review_note??'Excluded from activation picture'}</span></div>)}</div>{stagedItems.some(i=>i.schedule_status==='REVIEW_REQUIRED'||(i.event_kind==='ACTIVATION'&&i.match_status!=='MATCHED'))&&<div style={danger}><strong>Partial result:</strong> unresolved activation records will remain excluded and the feed will be marked PARTIAL. DASS will retain fail-safe visibility.</div>}<button type="button" disabled={pending||Boolean(staged.coverage_end&&new Date(staged.coverage_end)<=new Date())} onClick={publish} style={primary}>{pending?'Processing…':'Publish reviewed PIB picture'}</button><div style={discardRow}><input value={discardReason} onChange={e=>setDiscardReason(e.target.value.slice(0,500))} placeholder="Reason for discarding" style={input}/><button type="button" disabled={pending||discardReason.trim().length<5} onClick={discard} style={{...primary,marginTop:0,background:'#432328',borderColor:'#92535a'}}>Discard staged PIB</button></div></div></section>}{message&&<div role="status" style={success}>{message}</div>}{error&&<div role="alert" style={danger}>{error}</div>}</>}
const panel:React.CSSProperties={marginTop:'20px',border:'1px solid #203243',background:'#0b1722',borderRadius:'14px',padding:'16px'},eyebrow:React.CSSProperties={fontSize:'9px',letterSpacing:'.13em',color:'#8fdaf0',fontWeight:900},copy:React.CSSProperties={margin:'0 0 13px',fontSize:'11px',lineHeight:1.6,color:'#9fb1bc'},reviewBox:React.CSSProperties={marginTop:'14px',border:'1px solid #2b4657',borderRadius:'10px',padding:'13px'},stats:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:'8px'},warning:React.CSSProperties={marginTop:'10px',borderLeft:'3px solid #f59e0b',paddingLeft:'10px',fontSize:'10px',color:'#e6ca96',lineHeight:1.5},primary:React.CSSProperties={marginTop:'12px',border:'1px solid #3e718b',background:'#17384b',color:'#e5f8ff',borderRadius:'8px',padding:'10px 13px',fontWeight:850},stagedBox:React.CSSProperties={border:'1px solid rgba(245,158,11,.42)',background:'rgba(245,158,11,.055)',borderRadius:'13px',padding:'14px'},itemList:React.CSSProperties={marginTop:'13px',maxHeight:'420px',overflow:'auto',border:'1px solid #203243',borderRadius:'9px'},danger:React.CSSProperties={marginTop:'11px',borderLeft:'3px solid #ff5a64',padding:'10px',fontSize:'10px',lineHeight:1.5,color:'#ffc0c4',background:'rgba(255,90,100,.07)'},discardRow:React.CSSProperties={marginTop:'14px',borderTop:'1px solid #203243',paddingTop:'12px',display:'flex',gap:'8px',flexWrap:'wrap'},input:React.CSSProperties={flex:'1 1 240px',background:'#08131c',border:'1px solid #385267',borderRadius:'8px',color:'#edf5fb',padding:'9px'},success:React.CSSProperties={marginTop:'13px',borderLeft:'3px solid #4fd18b',padding:'10px',background:'rgba(79,209,139,.07)',color:'#a9e8c5',fontSize:'11px'}
function Stat({label,value}:{label:string;value:string}){return <div style={{border:'1px solid #1d3341',background:'#091720',borderRadius:'8px',padding:'9px'}}><div style={{fontSize:'8px',color:'#708998',textTransform:'uppercase',letterSpacing:'.1em'}}>{label}</div><div style={{marginTop:'4px',fontSize:'10px',lineHeight:1.4}}>{value}</div></div>}
