import type {OperationalAlert,AlertSeverity} from '../../lib/alerts/operational-alerts'

function utc(value:string|null){if(!value)return'Immediate attention';return new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))+' UTC'}
function colours(level:AlertSeverity){if(level==='CRITICAL')return{line:'#ff5a64',text:'#ffb3b8',bg:'rgba(255,90,100,.075)'};if(level==='WARNING')return{line:'#f59e0b',text:'#f5d08a',bg:'rgba(245,158,11,.07)'};return{line:'#46b9dc',text:'#a9e5f5',bg:'rgba(70,185,220,.065)'}}

export default function OperationalAlertCentre({alerts,audience}:{alerts:OperationalAlert[];audience:'Administrator'|'Operator'}){
  const critical=alerts.filter(a=>a.severity==='CRITICAL').length
  return <section aria-labelledby="operational-alerts" style={{marginTop:'18px',border:'1px solid #203746',background:'#0a1822',borderRadius:'13px',padding:'14px'}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:'12px',flexWrap:'wrap'}}><div><div style={{fontSize:'9px',letterSpacing:'.14em',color:'#8fdaf0',fontWeight:900}}>ALPHA 1.4.0 · OPERATIONAL ALERT CENTRE</div><h2 id="operational-alerts" style={{fontSize:'18px',margin:'5px 0 2px'}}>{audience} alerts</h2><div style={{fontSize:'10px',color:'#91a6b8'}}>Live, read-only alerts derived from the current DASS operational picture.</div></div><span style={{border:`1px solid ${critical?'rgba(255,90,100,.45)':'rgba(79,209,139,.38)'}`,color:critical?'#ffb3b8':'#84e8b0',background:critical?'rgba(255,90,100,.08)':'rgba(79,209,139,.07)',borderRadius:'999px',padding:'6px 9px',fontSize:'9px',fontWeight:900}}>{critical?`${critical} CRITICAL`:'NO CRITICAL ALERTS'}</span></div>
    <div style={{marginTop:'12px',display:'grid',gap:'8px'}}>{alerts.length?alerts.map(alert=>{const c=colours(alert.severity);const content=<><div style={{display:'flex',justifyContent:'space-between',gap:'10px',flexWrap:'wrap'}}><strong style={{fontSize:'11px',color:c.text}}>{alert.title}</strong><span style={{fontSize:'8px',fontWeight:900,color:c.text}}>{alert.severity} · {utc(alert.dueAt)}</span></div><div style={{marginTop:'4px',fontSize:'10px',lineHeight:1.5,color:'#b7c7d0'}}>{alert.detail}</div></>;return alert.href?<a key={alert.id} href={alert.href} style={{display:'block',textDecoration:'none',borderLeft:`3px solid ${c.line}`,background:c.bg,borderRadius:'7px',padding:'10px 11px'}}>{content}</a>:<article key={alert.id} style={{borderLeft:`3px solid ${c.line}`,background:c.bg,borderRadius:'7px',padding:'10px 11px'}}>{content}</article>}):<div style={{borderLeft:'3px solid #4fd18b',background:'rgba(79,209,139,.065)',borderRadius:'7px',padding:'11px',fontSize:'10px',color:'#a9e8c5'}}>No time-critical operational alerts are currently detected.</div>}</div>
  </section>
}
